/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EscrowSettings } from "./EscrowSettings";
export type { IEscrowSettings } from "./IEscrowSettings";
