/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { CarefulMath, CarefulMathInterface } from "../../src/CarefulMath";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "denominator",
        type: "uint256",
      },
    ],
    name: "PRBMath__MulDivOverflow",
    type: "error",
  },
] as const;

const _bytecode =
  "0x6084610051600b82828239805160001a6073146044577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063f8a8fd6d146038575b600080fd5b818015604357600080fd5b50604a604c565b005b56fea264697066735822122058a066d55f67ad933bc76d4ad7cfb7bc51dd3f8fa54ec6d177ef9d7185d7421464736f6c63430008180033";

type CarefulMathConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CarefulMathConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CarefulMath__factory extends ContractFactory {
  constructor(...args: CarefulMathConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CarefulMath & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CarefulMath__factory {
    return super.connect(runner) as CarefulMath__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CarefulMathInterface {
    return new Interface(_abi) as CarefulMathInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): CarefulMath {
    return new Contract(address, _abi, runner) as unknown as CarefulMath;
  }
}
