/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISecurityContext,
  ISecurityContextInterface,
} from "../../src/ISecurityContext";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISecurityContext__factory {
  static readonly abi = _abi;
  static createInterface(): ISecurityContextInterface {
    return new Interface(_abi) as ISecurityContextInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISecurityContext {
    return new Contract(address, _abi, runner) as unknown as ISecurityContext;
  }
}
