[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test-foundry"
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "solbase/=lib/solbase/src/",
  "solady/=lib/solady/src/",
  "hats-protocol/=lib/hats-protocol/"
]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${process.env.SEPOLIA_API_KEY}"
sepolia = "https://sepolia.infura.io/v3/${process.env.SEPOLIA_API_KEY}"
op_sepolia = "https://sepolia.optimism.io"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
